sudo: required
services:
  - docker

before_install:
  - docker build -t ortizjd-jmu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ortizjd-jmu/react-test npm test

after_success:
  - docker build -t ortizjd-jmu/multi-client ./client
  - docker build -t ortizjd-jmu/multi-nginx ./nginx
  - docker build -t ortizjd-jmu/multi-server ./server
  - docker build -t ortizjd-jmu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker tag ortizjd-jmu/multi-client:latest ortizjd/multi-docker:myfirstimagepush1
  - docker tag ortizjd-jmu/multi-nginx:latest ortizjd/multi-docker:myfirstimagepush2
  - docker tag ortizjd-jmu/multi-server:latest ortizjd/multi-docker:myfirstimagepush3
  - docker tag ortizjd-jmu/multi-worker:latest ortizjd/multi-docker:myfirstimagepush4

  - docker push ortizjd/multi-docker:myfirstimagepush1
  - docker push ortizjd/multi-docker:myfirstimagepush2
  - docker push ortizjd/multi-docker:myfirstimagepush3
  - docker push ortizjd/multi-docker:myfirstimagepush4

language: generic
